version: 2.1

executors:
    morpher-api-executor:
        docker:
            - image: openjdk:17-jdk-slim
        working_directory: ~/morpher-api

jobs:
    build:
        executor: morpher-api-executor
        steps:
            - checkout
            - run:
                name: Clean
                command: ./gradlew clean
            - run:
                name: Assemble
                command: ./gradlew compileJava compileTestJava assemble
            - run:
                name: Test
                command: ./gradlew test
            - run:
                name: Check
                command: ./gradlew check
            - run:
                name: Javadoc
                command: ./gradlew javadoc
            - run:
                name: Collect test results
                command: |
                    mkdir -p ~/morpher-api/build/test-report
                    find . -type f -name "TEST*.xml" -exec cp {} ~/morpher-api/build/test-report \;
                when: always
            - store_test_results:
                path: ~/morpher-api/build/test-report
            - persist_to_workspace:
                root: .
                paths:
                    - .

    publish-latest-docker-image:
        machine: true
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Build and publish latest Docker image
                command: ./scripts/build-docker-image.sh ./data/morpher-system.pb latest

    publish-tagged-docker-image:
        machine: true
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Build and publish tagged Docker image
                command: ./scripts/build-docker-image.sh ./data/morpher-system.pb

workflows:
    version: 2
    build-and-publish:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.+/
                    branches:
                        only: /.+/
            - publish-latest-docker-image:
                filters:
                    tags:
                        ignore: /.+/
                    branches:
                        only: master
                requires:
                    - build
            - publish-tagged-docker-image:
                filters:
                    tags:
                        only: /.+/
                    branches:
                        ignore: /.*/
                requires:
                    - build
